---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by AtomiX.
--- DateTime: 3/3/2022 5:57 PM
---

Config = {}

Config.AllowDebug = true -- Console Debug
Config.AllowNotify = true -- Allows Notifications

Config.ReviveDebug = true -- Allows to use command /reviveme
Config.MaxInjureCount = 1 -- Maximal count of incapitations

Config.CanHurtRun = false

Config.KnockoutTimer = 10 -- Time before you wake up from incapitation
Config.Revive = 20 -- Time before you respawn or get up
Config.InjureCounter = 60